source 'http://rubygems.org'
require 'rubygems'

gem 'rails', '3.1.3'
#gem "rake", "0.8.7" Windows computers seem to prefer this gem
gem 'awesome_print', :require => 'ap'
gem 'pg'
gem 'haml-rails'
gem 'haml-coffee-script'
gem 'coffee-filter'
gem 'jquery-rails'
gem 'simple_form'

group :development, :test do
  gem 'rspec-rails', '2.8.1'
  gem 'shoulda-matchers'
  gem 'annotate', '~> 2.4.1.beta'
  gem 'database_cleaner'
  gem 'factory_girl_rails', '1.4.0'
  gem 'capybara', '>= 1.1.2'
  gem 'selenium-webdriver'
end

group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end