  # Connect on a TCP socket. Omitted by default since the client uses a
common: &common
    adapter: postgresql
    username: postgres
    password: Austin1234
    host: localhost
    port: 5432
    
development:
    <<: *common
    database: ajaxrailsfullcrud_multiple_development

test:
    <<: *common
    database: ajaxrailsfullcrud_test

production:
    <<: *common
    database: ajaxrailsfullcrud_production
  
